# Generated by Django 3.2.18 on 2023-09-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20230923_0714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='bus_id',
        ),
        migrations.AddField(
            model_name='bus',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
