# Generated by Django 3.2.18 on 2023-09-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20230923_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='busid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
